apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-server
  namespace: default
  labels:
    app: identity-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: identity-server
  template:
    metadata:
      labels:
        app: identity-server
    spec:
      containers:
      - name: identity-server
        image: beyondtrust.azurecr.io/hemantksingh/identity-server:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: identity-server
  namespace: default
  labels:
    app: identity-server
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30720
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: identity-server
  sessionAffinity: None
  type: LoadBalancer