apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
    name: {{ azure_managed_identity }}              # The name of your Azure identity
spec:
    type: 0                                         # 0 for managed service identity
    resourceID: {{ azure_managed_identity_id }}
    clientID: {{ azure_managed_identity_clientId }} # The clientId of the Azure AD identity that you created earlier
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
    name: azure-pod-identity-binding
spec:
    azureIdentity: {{ azure_managed_identity }}     # The name of your Azure identity
    selector: azure-pod-identity-binding-selector